; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
board_build.filesystem = littlefs
board_build.f_cpu = 240000000L
monitor_port = COM3
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.4
	adafruit/Adafruit GFX Library@^1.11.9
	tzapu/WiFiManager@^2.0.17
	h2zero/NimBLE-Arduino@^2.5.0
	adafruit/Adafruit GC9A01A@^1.1.0
build_flags = 
	-D USER_SETUP_LOADED
	-D GC9A01_DRIVER
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=240
	-D TFT_MISO=-1
	-D TFT_MOSI=11
	-D TFT_SCLK=12
	-D TFT_CS=10
	-D TFT_DC=9
	-D TFT_RST=8
	-D SPI_FREQUENCY=40000000
	-D SPI_READ_FREQUENCY=20000000
